name: Deploy Fresh Backend to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: npm install and build
      run: |
        cd server
        npm ci
        
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'projectconnect-fresh'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './server'
