# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - projectconnect-frontend-parthd-2025

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install and build
        working-directory: ./client
        env:
          REACT_APP_API_URL: https://projectconnect-backend-parthd-2025.azurewebsites.net/api
        run: |
          npm install
          npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./client

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8AAEECA1B6024E4A859BF59EC06EA901 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FA2F1A1CEDBC4F0F951B89A8BF76ECFC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E8DBA2EA4AA045C3854E32C6DD6AEF79 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'projectconnect-frontend-parthd-2025'
          slot-name: 'Production'
          package: .
        env:
          REACT_APP_API_URL: https://projectconnect-backend-parthd-2025.azurewebsites.net/api
          NODE_ENV: production
